<?php
declare(strict_types=1);
function bhAssert(bool $condition,string $message):void{if(!$condition)throw new RuntimeException($message);}
$root=dirname(__DIR__);
$bridge=(string)file_get_contents($root.'/includes/amazon-returns/BridgeService.php');
$status=(string)file_get_contents($root.'/includes/amazon-returns/StatusBridgeService.php');
$runtime=(string)file_get_contents($root.'/includes/amazon-returns/Runtime.php');
$daemon=(string)file_get_contents($root.'/workers/amazon-returns/daemon.php');
$bridgeApi=(string)file_get_contents($root.'/api/amazon-returns/bridge.php');
$statusApi=(string)file_get_contents($root.'/api/amazon-returns/status-bridge.php');
$reader=(string)file_get_contents($root.'/scripts/amazon-returns/seller-central-safe-t-read-worker.mjs');
$runner=(string)file_get_contents($root.'/scripts/amazon-returns/run-seller-central-daily.sh');

bhAssert(str_contains($bridge,"'write_process_heartbeat'"),'Write bridge heartbeat must persist worker liveness.');
bhAssert(str_contains($status,"'read_process_heartbeat'"),'Read bridge heartbeat must persist worker liveness.');
bhAssert(str_contains($status,"'browser_auth'"),'Authenticated browser checks must persist separately from process liveness.');
bhAssert(str_contains($bridgeApi,"\$input['worker_id']"),'Write bridge endpoint must pass worker identity to heartbeat service.');
bhAssert(str_contains($statusApi,"\$input['worker_id']"),'Read bridge endpoint must pass worker identity to heartbeat service.');
bhAssert(str_contains($statusApi,"\$input['auth_status']"),'Status endpoint must pass non-secret browser auth outcome.');
bhAssert(str_contains($statusApi,'SELLER_CENTRAL_PRIMARY_STATUS_WORKER_ID'),'Status heartbeat must be bound to the configured primary VM worker.');
bhAssert(str_contains($bridgeApi,'SELLER_CENTRAL_PRIMARY_WRITE_WORKER_ID'),'Write bridge must be bound to the configured primary VM worker.');
bhAssert(str_contains($statusApi,"in_array(\$operation,['heartbeat','pull'],true)"),'Retired read workers must be rejected before heartbeat or pull.');
bhAssert(str_contains($bridgeApi,"in_array(\$operation,['heartbeat','pull'],true)"),'Retired write workers must be rejected before heartbeat or pull.');
bhAssert(str_contains($statusApi,"'IGNORED_WORKER'"),'Retired read bridge workers must be ignored before they can replace primary liveness.');
bhAssert(str_contains($bridgeApi,"'IGNORED_WORKER'"),'Retired write bridge workers must be ignored before they can claim jobs.');
$ignoredWorkerGuard=strpos($statusApi,"'IGNORED_WORKER'");
$statusHeartbeatCall=strpos($statusApi,'$service->heartbeat');
bhAssert($ignoredWorkerGuard!==false && $statusHeartbeatCall!==false && $ignoredWorkerGuard<$statusHeartbeatCall,'Primary worker guard must execute before heartbeat persistence.');
$writeIgnoredWorkerGuard=strpos($bridgeApi,"'IGNORED_WORKER'");
$writePullCall=strpos($bridgeApi,'$service->pull');
bhAssert($writeIgnoredWorkerGuard!==false && $writePullCall!==false && $writeIgnoredWorkerGuard<$writePullCall,'Primary write-worker guard must execute before job claiming.');
bhAssert(str_contains($reader,'--auth-check'),'Read worker must provide an authenticated browser health check.');
bhAssert(str_contains($reader,'auth_status: auth.status'),'Auth check must report the non-secret auth result to the backend.');
bhAssert(str_contains($runner,'--auth-check'),'Daily browser cycle must authenticate before draining jobs.');
bhAssert(str_contains($runtime,'BridgeLiveness.php'),'Runtime health must load authenticated bridge liveness logic.');
bhAssert(str_contains($runtime,"'seller_central_browser'"),'Health payload must expose Seller Central browser liveness.');
bhAssert(str_contains($runtime,'SELLER_CENTRAL_PRIMARY_STATUS_WORKER_ID'),'Runtime health must validate the configured primary VM worker.');
bhAssert(str_contains($runtime,"'DEGRADED'"),'Health must support a degraded state.');
bhAssert(str_contains($daemon,"in_array('DEGRADED',\$statuses,true)"),'Daemon aggregate status must preserve DEGRADED health.');
echo "bridge-heartbeat-contract-test: OK\n";
