<?php
declare(strict_types=1);
require_once __DIR__ . '/../../includes/AdminAuth.php';
require_once __DIR__ . '/../../includes/Csrf.php';
SvAmazonReturnsAdminAuth::requireLogin(false);
$csrf=SvAmazonReturnsCsrf::token('amazon_returns_intake');
?>
<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Registrar devolução Amazon</title>
<style>:root{font-family:Inter,system-ui,sans-serif;color:#17202a;background:#f4f6f8}*{box-sizing:border-box}body{margin:0}.wrap{max-width:720px;margin:auto;padding:18px}.panel{background:#fff;border:1px solid #e4e7ea;border-radius:14px;padding:18px;margin-bottom:14px}label{font-weight:700;display:block;margin:14px 0 6px}input,select,textarea,button{width:100%;font:inherit;padding:12px;border:1px solid #cfd4da;border-radius:10px}button{background:#17202a;color:#fff;font-weight:800;cursor:pointer}button:disabled{opacity:.55;cursor:wait}.row{display:grid;grid-template-columns:1fr auto;gap:8px}.row button{width:auto}.item{border:1px solid #e4e7ea;border-radius:10px;padding:12px;margin:8px 0;cursor:pointer}.item.active{border-color:#17202a;background:#f8fafc}.muted{color:#667085}.ok{color:#067647;font-weight:700}.err{color:#b42318;font-weight:700}.back{color:#17202a}@media(max-width:560px){.wrap{padding:10px}.panel{padding:14px}.row{grid-template-columns:1fr}.row button{width:100%}}</style></head><body><main class="wrap">
<p><a class="back" href="/admin/amazon-returns/">← Devoluções Amazon</a></p><h1>Registrar devolução recebida</h1>
<section class="panel"><label for="order">Número do pedido Amazon</label><input id="order" inputmode="numeric" placeholder="702-0000000-0000000" autocomplete="off"><div class="muted">Ou pesquise pela nota fiscal da venda.</div><label for="invoice">Número da NF de venda</label><div class="row"><input id="invoice" inputmode="numeric" maxlength="20" placeholder="Ex.: 123456" autocomplete="off"><button type="button" id="search">Localizar</button></div><div class="muted">Informe o pedido ou a NF. Se o pedido ainda não estiver no aplicativo, ele será consultado na Amazon neste momento.</div><div id="items"></div></section>
<form class="panel" id="form" enctype="multipart/form-data"><input type="hidden" name="csrf_token" value="<?=htmlspecialchars($csrf,ENT_QUOTES,'UTF-8')?>"><input type="hidden" name="operation_id" id="operation"><input type="hidden" name="case_id" id="case_id">
<div id="selected" class="muted">Localize e selecione um item antes de registrar.</div>
<label for="quantity">Quantidade correta recebida</label><input id="quantity" name="quantity_correct" type="number" min="0" step="1" value="1" required><div class="muted">Se chegou produto diferente ou embalagem vazia, informe 0. Em devolução parcial, informe somente a quantidade correta que chegou.</div>
<label for="condition">Como o produto chegou?</label><select id="condition" name="condition" required><option value="OK">Íntegro</option><option value="DAMAGED">Danificado</option><option value="USED">Usado</option><option value="WRONG_ITEM">Produto diferente</option><option value="INCOMPLETE">Incompleto</option><option value="EMPTY_PACKAGE">Embalagem vazia</option></select>
<label for="note">Observação</label><textarea id="note" name="note" rows="4" maxlength="2000" placeholder="Descreva somente o que você observou na conferência."></textarea>
<label for="photos">Fotos</label><input id="photos" name="photos[]" type="file" accept="image/jpeg,image/png,image/webp" multiple><div class="muted">Obrigatórias quando houver divergência. Máximo de 6 fotos, 8 MB cada.</div>
<p id="message"></p><button type="submit" id="submit-receipt">Confirmar recebimento</button></form></main>
<script>
const csrf=<?=json_encode($csrf,JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT)?>;const operation=document.querySelector('#operation');const msg=document.querySelector('#message');const caseId=document.querySelector('#case_id');const selected=document.querySelector('#selected');const searchButton=document.querySelector('#search');const submitButton=document.querySelector('#submit-receipt');const uuid=()=>crypto.randomUUID();operation.value=uuid();
const intakeStatusLabels={REFUND_DETECTED:'Reembolso identificado',AWAITING_RETURN:'Aguardando devolução',IN_TRANSIT:'Em transporte',CARRIER_DELIVERED_PENDING_PHYSICAL:'Transportadora indica entrega; conferência pendente',RECEIVED_OK:'Recebido sem divergência',RECEIVED_DISCREPANT:'Recebido com divergência',SAFE_T_ELIGIBLE:'Pode solicitar ressarcimento',SAFE_T_READY:'Pronto para solicitar ressarcimento',SAFE_T_SUBMITTED:'Ressarcimento solicitado',SAFE_T_APPROVED:'Ressarcimento aprovado',SAFE_T_DENIED:'Ressarcimento negado',CREDIT_PENDING:'Aguardando crédito',RECOVERED:'Valor recuperado',POLICY_REVIEW_REQUIRED:'Em análise',BLOCKED_REVIEW:'Precisa de decisão'};
function humanIntakeStatus(value){const key=String(value||'');return intakeStatusLabels[key]||'Situação em atualização';}
function friendlyIntakeError(value){const raw=String(value||'');if(/CSRF/i.test(raw))return 'Sua sessão precisa ser atualizada. Recarregue a página e tente novamente.';if(/Banco indisponível/i.test(raw))return 'O sistema está temporariamente indisponível. Tente novamente em instantes.';if(/^[A-Z0-9_:-]+$/.test(raw)||/[a-z]+_[a-z0-9_]+/i.test(raw))return 'Não foi possível concluir esta ação. Tente novamente.';return raw||'Não foi possível concluir esta ação.';}
function setMsg(t,ok=false){msg.textContent=t;msg.className=ok?'ok':'err'}
function expectedQuantity(c){return Number(c.quantity_refunded||0)>0?Number(c.quantity_refunded):Math.max(1,Number(c.quantity_ordered||0));}
function choose(c,el){caseId.value=c.id;document.querySelectorAll('.item').forEach(x=>x.classList.remove('active'));el.classList.add('active');const total=expectedQuantity(c);const pending=Math.max(0,total-Number(c.quantity_received||0));document.querySelector('#quantity').max=String(pending);document.querySelector('#quantity').value=String(Math.min(1,pending));selected.textContent=`Pedido ${c.amazon_order_id} · ${c.sku||c.asin||c.amazon_order_item_id} · faltam ${pending} unidade(s) para conferir`}
document.querySelector('#search').addEventListener('click',async()=>{msg.textContent='';caseId.value='';selected.textContent='Localize e selecione um item antes de registrar.';const order=document.querySelector('#order').value.trim();const invoice=document.querySelector('#invoice').value.trim();if(order!==''&&!/^\d{3}-\d{7}-\d{7}$/.test(order)){setMsg('Informe um número de pedido Amazon válido.');return}if(invoice!==''&&!/^\d{1,20}$/.test(invoice)){setMsg('Informe somente os números da NF de venda.');return}if(order===''&&invoice===''){setMsg('Informe o número do pedido Amazon ou da NF de venda.');return}searchButton.disabled=true;searchButton.textContent='Localizando…';try{const r=await fetch('/admin/amazon-returns/api/intake-lookup.php',{method:'POST',credentials:'same-origin',cache:'no-store',headers:{'content-type':'application/json','X-CSRF-Token':csrf},body:JSON.stringify({order_id:order,sales_invoice_number:invoice,csrf_token:csrf})});const j=await r.json().catch(()=>({}));const box=document.querySelector('#items');box.replaceChildren();if(!r.ok||!j.success){setMsg(friendlyIntakeError(j.error));return}if(!(j.cases||[]).length){setMsg(order?'Nenhuma devolução encontrada para este pedido na Amazon.':'Nenhuma devolução encontrada para esta NF.');return}for(const c of j.cases){const el=document.createElement('div');el.className='item';const total=expectedQuantity(c);el.textContent=`${c.sku||c.asin||c.amazon_order_item_id} · ${humanIntakeStatus(c.state)} · recebido ${Number(c.quantity_received||0)}/${total}`;el.addEventListener('click',()=>choose(c,el));box.append(el)}if(j.cases.length===1)box.firstElementChild.click();if(j.synced)setMsg('Pedido localizado na Amazon e disponibilizado para registrar o recebimento.',true)}catch(err){setMsg(friendlyIntakeError(err.message))}finally{searchButton.disabled=false;searchButton.textContent='Localizar'}});
document.querySelector('#condition').addEventListener('change',e=>{const discrepancy=e.target.value!=='OK';document.querySelector('#photos').required=discrepancy;if(['WRONG_ITEM','EMPTY_PACKAGE'].includes(e.target.value))document.querySelector('#quantity').value='0'});
document.querySelector('#form').addEventListener('submit',async e=>{e.preventDefault();if(!caseId.value){setMsg('Selecione o item recebido.');return}const condition=document.querySelector('#condition').value;if(condition!=='OK'&&!document.querySelector('#photos').files.length){setMsg('Anexe ao menos uma foto da divergência.');return}const fd=new FormData(e.target);submitButton.disabled=true;const originalLabel=submitButton.textContent;submitButton.textContent='Registrando…';try{const r=await fetch('/admin/amazon-returns/api/intake.php',{method:'POST',body:fd,headers:{'X-CSRF-Token':csrf},credentials:'same-origin'});const j=await r.json().catch(()=>({}));if(!r.ok||!j.success)throw new Error(friendlyIntakeError(j.error));setMsg(j.duplicate?'Este recebimento já estava registrado; nenhuma informação foi duplicada.':'Recebimento registrado com sucesso.',true);operation.value=uuid()}catch(err){setMsg(friendlyIntakeError(err.message))}finally{submitButton.disabled=false;submitButton.textContent=originalLabel}});
</script></body></html>